pollme_app/pollme_app/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('time/',views.current_datetime,name='date_time'),
    path('polls/',include('polls.urls',namespace='polls')),
]

pollme_app/polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
    path('list/',views.poll_list,name='poll_list'),
    path('detail/<int:poll_id>',views.poll_details,name='poll_detail'),
    path('detail/<int:poll_id>/vote/',views.poll_vote,name='poll_vote'),
]

pollme_app/polls/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    text     = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

class Choice(models.Model):
    questions   = models.ForeignKey(Poll,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    vote        = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.questions.text[:25],self.choice_text[:25])

pollme_app/pollme_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

import datetime

def home(request):
	now=datetime.datetime.now()
	context={'now_time':now}
	return render(request,'home.html',context) 

def current_datetime(request):
	now=datetime.datetime.now()
	html="<html><body>It is now %s.</body></html>" %now
	return HttpResponse(html)

pollme_app/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Poll,Choice
# Create your views here.


def poll_list(request):
    polls=Poll.objects.all()
    context={'polls':polls}
    return render(request,'polls/poll_list.html',context)

def poll_details(request,poll_id):
    poll=get_object_or_404(Poll,id=poll_id)
    context={"poll":poll}

    return render(request,'polls/poll_detail.html',context)

def poll_vote(request,poll_id):
    choice=Choice.objects.get(id=poll_id)
    choice.vote+=1
    choice.save()
    return HttpResponse("Poll Id {} ".format(poll_id))
    

pollme_app/polls/templates/polls/poll_detail.html
<!doctype html>

{% extends 'base.html' %}

{% block content %}
    <h1>Poll Detail Page</h1>
    {{ poll }}
    <form action="{% url 'polls:poll_vote' poll.id %}" method="post">
        {% csrf_token %}
    {% for choice in poll.choice_set.all%}    
        <input type="radio"
                name="choice"
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label>
        <br>
        <input type="submit" value="Vote">
    {% endfor %}    
    </form> 
{% endblock %}

pollme_app/polls/templates/polls/poll_list.html
<!doctype html>

<!---
Author Name:-Amit kadivar
Created Date:-6/7/2018
Created by:-
-->

{% extends 'base.html' %}
{% load static %}
{% block title %}Polls | poll_list{% endblock %}
{% block bootstrap %}
  {{ block.super }} 

{% endblock %}
{% block container-fluid %}
  
  {% block navbar%}
  {{ block.super }}
  {% endblock %}
  {% block content %}
  <div class="container">
    <h1 class="text-center">Welcome to Poll List </h1>
    <div class="row">
      <div class="col-sm-8 offset-sm-2"> 
        {% for poll in polls %}
         <a href=" {% url 'polls:poll_detail' poll.id %}" class="list-group-item list-group-item-action">{{ poll }}</a>
         {% endfor %}
      </div>
    </div>
   </div>

  {% endblock %}
{% endblock %}
    


pollme_app/templates/base.html
<!doctype html>
<!--
Author Name:-Amit kadivar
Created Date:-6/7/2018
Created by:-
-->
{% load static %}

<html lang="en">
  <head>
    <title>{% block title %} Home|page{% endblock %}</title>
    {% block bootstrap %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
   
    <link rel="stylesheet" 
          href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" 
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" 
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  {% endblock %}
</head>
  <body>
                                    <!--Nav Bar-->
    {% block container-fluid %}
    <div class="container-fluid">
        {% block navbar%}
                
           {% include 'include/navbar.html' %}
        {% endblock %}
     
        {% block content %}
          <h1>Welcome to Home Page!!!</h1>
          <p>what is today? </p>
          <p>{{ now_time }}</p>
        {% endblock %}
    </div>
    {% endblock %}
  </body>
</html>



pollme_app/templates/home.html
<!doctype html>
{% extends 'base.html' %}
{% load static %}
{% block title %}Polls | Home{% endblock %}
{% block bootstrap %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
{{ block.super }}  
  
{% endblock %}
{% block container-fluid %}
  
  {% block navbar%}
  {{ block.super }}
  {% endblock %}
  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col"> 
          <div id="home-content">
            <h1>PollMe - Get Start !</h1>
            <h3> Your Vote is important !</h3>
            <hr>
            <button type="button" class="btn btn-light btn-lg">Get Started!</button>
          </div>
        </div>  
      </div>
    </div>
  {% endblock %}
{% endblock %}



pollme_app/templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">logo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:poll_list'%}">Polls</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'date_time'%}">Time</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        </div>
    </nav>